# Generated by Django 4.0.6 on 2022-08-04 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_message_icon_message_image_alter_message_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='user_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
